# NumPy

Numerical Pyhton

In [1]:
import numpy as np

In [2]:
[1,2,3,4]

[1, 2, 3, 4]

In [33]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [34]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [35]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
a.ndim

2

In [37]:
a.shape

(3, 4)

In [7]:
b = np.array(
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]],
        [[9, 10], [11, 12]]
    ]
)

b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [8]:
b.ndim

3

In [9]:
b.shape

(3, 2, 2)

# Array

- np.array()
- np.zeros()
- np.ones()
- np.empty()
- np.arange()

In [10]:
np.array([1, 2, 3])

array([1, 2, 3])

In [11]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [12]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [38]:
np.empty((2, 2))

array([[1., 1.],
       [1., 1.]])

In [14]:
range(5)

range(0, 5)

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

# Add, Remove, and Sort

- np.append()
- np.delete()
- np.sort()

In [16]:
arr = np.arange(8)
mylist = list(range(8))
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
mylist.append([1, 2])
mylist

[0, 1, 2, 3, 4, 5, 6, 7, [1, 2]]

In [18]:
np.append(arr, [[1, 2]])


array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [19]:
arr = np.append(arr, [1, 2])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [20]:
np.delete(arr,1)

array([0, 2, 3, 4, 5, 6, 7, 1, 2])

In [21]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [22]:
np.sort(arr)

array([0, 1, 1, 2, 2, 3, 4, 5, 6, 7])

In [23]:
print("dim", arr.ndim)
print("size", arr.size)
print("shape", arr.shape)

dim 1
size 10
shape (10,)


In [24]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
print("dim", a.ndim)
print("size", a.size)
print("shape", a.shape)

dim 2
size 12
shape (3, 4)


In [26]:
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [27]:
print("dim", b.ndim)
print("size", b.size)
print("shape", b.shape)

dim 3
size 12
shape (3, 2, 2)


In [28]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [29]:
print("dim", array_example.ndim)
print("size", array_example.size)
print("shape", array_example.shape)

dim 3
size 24
shape (3, 2, 4)


# Reshape

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [31]:
arr.shape

(10,)

In [32]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [1, 2]])

In [40]:
arr3 = arr.reshape(5, 2)

In [42]:
arr3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [1, 2]])

Convert 1D to 2D

- np.newaxis
- np.expand_dims

In [44]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [45]:
arr.shape

(10,)

In [46]:
arr4 = arr[np.newaxis, :]

In [48]:
arr4

array([[0, 1, 2, 3, 4, 5, 6, 7, 1, 2]])

In [50]:
arr4.ndim

2

In [52]:
arr4.shape

(1, 10)

In [54]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
a.shape

(3, 4)

In [58]:
np.expand_dims(a, axis=0).shape

(1, 3, 4)

In [59]:
a[np.newaxis, :].shape

(1, 3, 4)

### Indexing and Slicing

arr[start:stop:step]

In [61]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [63]:
arr[8]

1

In [65]:
arr[4:]

array([4, 5, 6, 7, 1, 2])

In [67]:
arr > 2

array([False, False, False,  True,  True,  True,  True,  True, False,
       False])

In [69]:
arr[arr > 2]

array([3, 4, 5, 6, 7])

In [71]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
a < 8

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [75]:
a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [77]:
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [79]:
a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [81]:
a % 3 == 0

array([[False, False,  True, False],
       [False,  True, False, False],
       [ True, False, False,  True]])

In [83]:
(a % 2 == 0) & (a % 3 == 0)

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False,  True]])

In [85]:
a[(a % 2 == 0) & (a % 3 == 0)]

array([ 6, 12])

## Creating from Existing Data

- np.vstack()
- np.hstack()
- np.vsplit()
- np.hsplit()
- .view()
- .copy()

In [87]:
arr1 = arr[3:8]

In [89]:
arr1

array([3, 4, 5, 6, 7])

In [91]:
a_1 = np.array([[1, 1], [2, 2]])
print(a_1.shape)
a_1

(2, 2)


array([[1, 1],
       [2, 2]])

In [93]:
a_2 = np.array([[3, 3], [4, 4]])
print(a_2.shape)
a_2

(2, 2)


array([[3, 3],
       [4, 4]])

In [95]:
np.vstack([a_1, a_2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [97]:
np.hstack([a_1, a_2])

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [99]:
arrsplit = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [101]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [103]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [105]:
np.hsplit(a, 2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [107]:
np.vsplit(a, 3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [109]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [111]:
b = a

In [113]:
print(id(a))
print(id(b))
print(id(a) == id(b))

1560479389936
1560479389936
True


In [115]:
b = a.view()

In [117]:
print(id(a))
print(id(b))
print(id(a) == id(b))

1560479389936
1560485203760
False


In [119]:
c = a.copy()

In [121]:
print(id(a))
print(id(c))
print(id(a) == id(c))

1560479389936
1560485203472
False


## Basic Array Operations

In [123]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [125]:
arr + 1

array([1, 2, 3, 4, 5, 6, 7, 8, 2, 3])

In [127]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35,  5, 10])

In [129]:
[1, 2, 3] * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [131]:
[1, 2, 3] + [5]

[1, 2, 3, 5]

In [133]:
arr + np.array([5])

array([ 5,  6,  7,  8,  9, 10, 11, 12,  6,  7])

In [134]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 0.5, 1. ])

In [135]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [138]:
data = np.array([1, 2])
data

array([1, 2])

In [140]:
ones = np.ones(2)
ones

array([1., 1.])

In [142]:
data + ones

array([2., 3.])

In [144]:
data * ones

array([1., 2.])

### Broadcasting

In [145]:
data * 2

array([2, 4])

In [147]:
data + 2

array([3, 4])

### Array Operations

- data.max()
- data.min()
- data.sum()
- data.mean()
- data.std()
- data.var()

In [149]:
%%timeit
sum([1, 2, 3, 4])

297 ns ± 135 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [151]:
%%timeit
np.arange(1, 5).sum()

4.93 µs ± 744 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [153]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 1, 2])

In [155]:
print(arr.sum())
print(arr.max())
print(arr.min())

31
7
0


In [157]:
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))

31
7
0


### Matrices

In [159]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [161]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [163]:
np.random.random((3, 2))

array([[0.00646661, 0.06474913],
       [0.55588639, 0.52356151],
       [0.72173421, 0.75241959]])

### Matrix Arithmetic

In [165]:
data = np.arange(1, 5).reshape(2, 2)
ones = np.ones((2, 2))
ones_row = np.ones((1, 2))

print(data)
print(ones)
print(ones_row)

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]]


In [167]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [169]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


### Dot Product

In [171]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


# perkalian matrix
(2, 3) * (3, 2)  # a_1 * a_2

(3, 2) * (2, 3)  # a_2 * a_1

In [173]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [174]:
np.dot(a_2, a_1)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

### Matrix Indexing

In [176]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [178]:
a[0][0]

1

In [180]:
a[1][2]

7

In [182]:
a[2][-1]

12

In [184]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


### Matrix Aggregation

In [186]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [188]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [189]:
data.shape

(3, 2)

In [191]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [193]:
print(data.sum(axis=0))
print(data.sum(axis=1))

[ 9 12]
[ 3  7 11]


### Transposing

In [195]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [197]:
data.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [199]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [201]:
data.shape

(3, 2)

In [203]:
data.reshape((6,))

array([1, 2, 3, 4, 5, 6])

In [205]:
data.reshape((6, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [207]:
data.reshape((1, 6))

array([[1, 2, 3, 4, 5, 6]])

In [209]:
np.arange(15).reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [211]:
np.linspace(0, 50, num=20).reshape((5, 4))

array([[ 0.        ,  2.63157895,  5.26315789,  7.89473684],
       [10.52631579, 13.15789474, 15.78947368, 18.42105263],
       [21.05263158, 23.68421053, 26.31578947, 28.94736842],
       [31.57894737, 34.21052632, 36.84210526, 39.47368421],
       [42.10526316, 44.73684211, 47.36842105, 50.        ]])

### N Dimensional Array

In [213]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [215]:
ndarr.shape

(2, 2, 2)

In [217]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [219]:
randomarr = np.random.random((4, 3, 2))
randomarr

array([[[0.90408272, 0.82272264],
        [0.32794314, 0.23688771],
        [0.88620031, 0.79528171]],

       [[0.52921528, 0.58677689],
        [0.40213073, 0.79969399],
        [0.64695273, 0.56485119]],

       [[0.73597535, 0.44957768],
        [0.64911013, 0.80120634],
        [0.02984299, 0.91855819]],

       [[0.98367962, 0.94940015],
        [0.11913163, 0.29559237],
        [0.62056519, 0.08730658]]])

In [221]:
randomarr.flatten()

array([0.90408272, 0.82272264, 0.32794314, 0.23688771, 0.88620031,
       0.79528171, 0.52921528, 0.58677689, 0.40213073, 0.79969399,
       0.64695273, 0.56485119, 0.73597535, 0.44957768, 0.64911013,
       0.80120634, 0.02984299, 0.91855819, 0.98367962, 0.94940015,
       0.11913163, 0.29559237, 0.62056519, 0.08730658])

In [223]:
randomarr.reshape(-1)

array([0.90408272, 0.82272264, 0.32794314, 0.23688771, 0.88620031,
       0.79528171, 0.52921528, 0.58677689, 0.40213073, 0.79969399,
       0.64695273, 0.56485119, 0.73597535, 0.44957768, 0.64911013,
       0.80120634, 0.02984299, 0.91855819, 0.98367962, 0.94940015,
       0.11913163, 0.29559237, 0.62056519, 0.08730658])

In [225]:
randomarr.reshape(24,)

array([0.90408272, 0.82272264, 0.32794314, 0.23688771, 0.88620031,
       0.79528171, 0.52921528, 0.58677689, 0.40213073, 0.79969399,
       0.64695273, 0.56485119, 0.73597535, 0.44957768, 0.64911013,
       0.80120634, 0.02984299, 0.91855819, 0.98367962, 0.94940015,
       0.11913163, 0.29559237, 0.62056519, 0.08730658])